// Generated by gencpp from file rcnn_ros/points.msg
// DO NOT EDIT!


#ifndef RCNN_ROS_MESSAGE_POINTS_H
#define RCNN_ROS_MESSAGE_POINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rcnn_ros/point.h>

namespace rcnn_ros
{
template <class ContainerAllocator>
struct points_
{
  typedef points_<ContainerAllocator> Type;

  points_()
    : points()  {
    }
  points_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rcnn_ros::point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rcnn_ros::point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::rcnn_ros::points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcnn_ros::points_<ContainerAllocator> const> ConstPtr;

}; // struct points_

typedef ::rcnn_ros::points_<std::allocator<void> > points;

typedef boost::shared_ptr< ::rcnn_ros::points > pointsPtr;
typedef boost::shared_ptr< ::rcnn_ros::points const> pointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcnn_ros::points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcnn_ros::points_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rcnn_ros::points_<ContainerAllocator1> & lhs, const ::rcnn_ros::points_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rcnn_ros::points_<ContainerAllocator1> & lhs, const ::rcnn_ros::points_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rcnn_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rcnn_ros::points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcnn_ros::points_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcnn_ros::points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcnn_ros::points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcnn_ros::points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcnn_ros::points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcnn_ros::points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce136a87e01d93db92be5dd91e0f8f1";
  }

  static const char* value(const ::rcnn_ros::points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce136a87e01d93dULL;
  static const uint64_t static_value2 = 0xb92be5dd91e0f8f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rcnn_ros::points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcnn_ros/points";
  }

  static const char* value(const ::rcnn_ros::points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcnn_ros::points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcnn_ros/point[] points\n"
"\n"
"================================================================================\n"
"MSG: rcnn_ros/point\n"
"int32 point\n"
;
  }

  static const char* value(const ::rcnn_ros::points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcnn_ros::points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcnn_ros::points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcnn_ros::points_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rcnn_ros::point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCNN_ROS_MESSAGE_POINTS_H
